/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,html}",
    "./public/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        "ember-orange": "#ff5a2f",
        "ember-orange-link": "#f15b2b",
        "carbon-black": "#000000",
        "graphite": "#1f1f1f",
        "slate-dark": "#333333",
        "stone": "#555555",
        "pewter": "#707070",
        "steel": "#a5a5a5",
        "mist": "#b7bfc1",
        "cloud": "#cbcbcb",
        "fog": "#dddddd",
        "paper": "#e5e7eb",
        "pearl": "#f5f5f5",
        "canvas-white": "#ffffff",
      },
      fontFamily: {
        sans: [
          "'Plus Jakarta Sans'",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
      },
      fontSize: {
        "caption": ["12px", { lineHeight: "1.6" }],
        "body-sm": ["14px", { lineHeight: "1.5" }],
        "body": ["16px", { lineHeight: "1.64" }],
        "subheading": ["20px", { lineHeight: "1.5" }],
        "heading-sm": ["24px", { lineHeight: "1.45" }],
        "heading": ["32px", { lineHeight: "1.4" }],
        "heading-lg": ["50px", { lineHeight: "1.34" }],
        "display": ["80px", { lineHeight: "1.34" }],
      },
      fontWeight: {
        light: 300,
        regular: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
      },
      spacing: {
        4: "4px",
        8: "8px",
        12: "12px",
        16: "16px",
        20: "20px",
        24: "24px",
        28: "28px",
        32: "32px",
        36: "36px",
        40: "40px",
        48: "48px",
        60: "60px",
        80: "80px",
        120: "120px",
        208: "208px",
      },
      borderRadius: {
        "nav": "30px",
        "cards": "20px",
        "badges": "20px",
        "images": "20px",
        "buttons": "30px",
        "headings": "100px",
      },
      boxShadow: {
        "md": "0px 4px 10px 0px rgba(0, 0, 0, 0.25)",
      },
    },
  },
  plugins: [],
};